### ISSUE TITLE
getting some error and not able to find what is the error can you please help me out seeing below error

### ISSUE THREAD

**Issue by naveenkk944** [2015xli/DBN#1]
------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magics\execution.py in run(self, parameter_s, runner, file_finder)
    702             fpath = arg_lst[0]
--> 703             filename = file_finder(fpath)
    704         except IndexError:

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\utils\path.py in get_py_filename(name, force_win32)
    108     else:
--> 109         raise IOError('File `%r` not found.' % name)
    110 

OSError: File `"'activation.ipynb'.py"` not found.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
~\Desktop\sandlogic_tasks\deep_belief_net\DBN\RBM.ipynb in <module>
      1 from IPython.core.debugger import set_trace
      2 
----> 3 get_ipython().run_line_magic('run', "'activation.ipynb'")
      4 import numpy as np
      5 import pickle

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2325                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2326             with self.builtin_trap:
-> 2327                 result = fn(*args, **kwargs)
   2328             return result
   2329 

<decorator-gen-53> in run(self, parameter_s, runner, file_finder)

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magics\execution.py in run(self, parameter_s, runner, file_finder)
    712             if os.name == 'nt' and re.match(r"^'.*'$",fpath):
    713                 warn('For Windows, use double quotes to wrap a filename: %run "mypath\\myfile.py"')
--> 714             raise Exception(msg)
    715         except TypeError:
    716             if fpath in sys.meta_path:

Exception: File `"'activation.ipynb'.py"` not found.

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magics\execution.py in run(self, parameter_s, runner, file_finder)
    702             fpath = arg_lst[0]
--> 703             filename = file_finder(fpath)
    704         except IndexError:

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\utils\path.py in get_py_filename(name, force_win32)
    108     else:
--> 109         raise IOError('File `%r` not found.' % name)
    110 

OSError: File `"'activation.ipynb'.py"` not found.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
~\Desktop\sandlogic_tasks\deep_belief_net\DBN\RBM_Classification.ipynb in <module>
----> 1 get_ipython().run_line_magic('run', '"RBM.ipynb"')
      2 
      3 class RBM_Classification(RBM):
      4     # n_k is the number of classes
      5     def __init__(self, n_x, n_h, n_k, n_d=1, W=None, b=None, c=None, k=1):

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2325                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2326             with self.builtin_trap:
-> 2327                 result = fn(*args, **kwargs)
   2328             return result
   2329 

<decorator-gen-53> in run(self, parameter_s, runner, file_finder)

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magics\execution.py in run(self, parameter_s, runner, file_finder)
    722             with preserve_keys(self.shell.user_ns, '__file__'):
    723                 self.shell.user_ns['__file__'] = filename
--> 724                 self.shell.safe_execfile_ipy(filename, raise_exceptions=True)
    725             return
    726 

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in safe_execfile_ipy(self, fname, shell_futures, raise_exceptions)
   2812                     result = self.run_cell(cell, silent=True, shell_futures=shell_futures)
   2813                     if raise_exceptions:
-> 2814                         result.raise_error()
   2815                     elif not result.success:
   2816                         break

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in raise_error(self)
    329             raise self.error_before_exec
    330         if self.error_in_exec is not None:
--> 331             raise self.error_in_exec
    332 
    333     def __repr__(self):

    [... skipping hidden 1 frame]

~\Desktop\sandlogic_tasks\deep_belief_net\DBN\RBM_Classification.ipynb in <module>
      1 from IPython.core.debugger import set_trace
      2 
----> 3 get_ipython().run_line_magic('run', "'activation.ipynb'")
      4 import numpy as np
      5 import pickle

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2325                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2326             with self.builtin_trap:
-> 2327                 result = fn(*args, **kwargs)
   2328             return result
   2329 

<decorator-gen-53> in run(self, parameter_s, runner, file_finder)

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magics\execution.py in run(self, parameter_s, runner, file_finder)
    712             if os.name == 'nt' and re.match(r"^'.*'$",fpath):
    713                 warn('For Windows, use double quotes to wrap a filename: %run "mypath\\myfile.py"')
--> 714             raise Exception(msg)
    715         except TypeError:
    716             if fpath in sys.meta_path:

Exception: File `"'activation.ipynb'.py"` not found.

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magics\execution.py in run(self, parameter_s, runner, file_finder)
    702             fpath = arg_lst[0]
--> 703             filename = file_finder(fpath)
    704         except IndexError:

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\utils\path.py in get_py_filename(name, force_win32)
    108     else:
--> 109         raise IOError('File `%r` not found.' % name)
    110 

OSError: File `"'activation.ipynb'.py"` not found.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-2-25598f99c7d5> in <module>
----> 1 get_ipython().run_line_magic('run', '"RBM_Classification.ipynb"')
      2 
      3 class DBN_Classification(RBM_Classification):
      4     # n_k is the number of classes, n_d is the # of dots representing one class
      5     def __init__(self, n_x, layers, n_k=10, n_d=1, k=1, mean_field=True):

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2325                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2326             with self.builtin_trap:
-> 2327                 result = fn(*args, **kwargs)
   2328             return result
   2329 

<decorator-gen-53> in run(self, parameter_s, runner, file_finder)

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magics\execution.py in run(self, parameter_s, runner, file_finder)
    722             with preserve_keys(self.shell.user_ns, '__file__'):
    723                 self.shell.user_ns['__file__'] = filename
--> 724                 self.shell.safe_execfile_ipy(filename, raise_exceptions=True)
    725             return
    726 

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in safe_execfile_ipy(self, fname, shell_futures, raise_exceptions)
   2812                     result = self.run_cell(cell, silent=True, shell_futures=shell_futures)
   2813                     if raise_exceptions:
-> 2814                         result.raise_error()
   2815                     elif not result.success:
   2816                         break

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in raise_error(self)
    329             raise self.error_before_exec
    330         if self.error_in_exec is not None:
--> 331             raise self.error_in_exec
    332 
    333     def __repr__(self):

    [... skipping hidden 1 frame]

<ipython-input-2-38d9d28a5a07> in <module>
----> 1 get_ipython().run_line_magic('run', '"RBM.ipynb"')
      2 
      3 class RBM_Classification(RBM):
      4     # n_k is the number of classes
      5     def __init__(self, n_x, n_h, n_k, n_d=1, W=None, b=None, c=None, k=1):

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2325                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2326             with self.builtin_trap:
-> 2327                 result = fn(*args, **kwargs)
   2328             return result
   2329 

<decorator-gen-53> in run(self, parameter_s, runner, file_finder)

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magics\execution.py in run(self, parameter_s, runner, file_finder)
    722             with preserve_keys(self.shell.user_ns, '__file__'):
    723                 self.shell.user_ns['__file__'] = filename
--> 724                 self.shell.safe_execfile_ipy(filename, raise_exceptions=True)
    725             return
    726 

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in safe_execfile_ipy(self, fname, shell_futures, raise_exceptions)
   2812                     result = self.run_cell(cell, silent=True, shell_futures=shell_futures)
   2813                     if raise_exceptions:
-> 2814                         result.raise_error()
   2815                     elif not result.success:
   2816                         break

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in raise_error(self)
    329             raise self.error_before_exec
    330         if self.error_in_exec is not None:
--> 331             raise self.error_in_exec
    332 
    333     def __repr__(self):

    [... skipping hidden 1 frame]

<ipython-input-2-a46754260696> in <module>
      1 from IPython.core.debugger import set_trace
      2 
----> 3 get_ipython().run_line_magic('run', "'activation.ipynb'")
      4 import numpy as np
      5 import pickle

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2325                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2326             with self.builtin_trap:
-> 2327                 result = fn(*args, **kwargs)
   2328             return result
   2329 

<decorator-gen-53> in run(self, parameter_s, runner, file_finder)

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

c:\users\naveen kumar k\appdata\local\programs\python\python37\lib\site-packages\IPython\core\magics\execution.py in run(self, parameter_s, runner, file_finder)
    712             if os.name == 'nt' and re.match(r"^'.*'$",fpath):
    713                 warn('For Windows, use double quotes to wrap a filename: %run "mypath\\myfile.py"')
--> 714             raise Exception(msg)
    715         except TypeError:
    716             if fpath in sys.meta_path:

Exception: File `"'activation.ipynb'.py"` not found.

**Comment by 2015xli** [comment]
The error message: "Exception: File "'activation.ipynb'.py" not found."  It is the problem of your Windows platform that does not support single quote 'filename'. I've made the change to double quotes "filename".
